version: "3.3"
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888"
    volumes:
      - .:/python-docker
  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    image: nginx:latest
    ports:
      - ${NGINX_PORTS}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
